### ISSUE TITLE
viewSavings displays negative result

### ISSUE THREAD

**Issue by yunjun199321** [CS2103-AY1819S2-W17-4/main#96]
1. set a budget of $1000 on 27/Mar/2019
2. add an expense of $500 on 27/Mar/2019
3. add a saving of $100 on 27/Mar/2019
4. view saving shows $-400

@kev-inc

**Comment by kev-inc** [comment]
The reason view savings show -$400 is because savings is calculated as all of the allowance (inflow) minus all of the expenses (outflow). In this case, expense of 500 is greater than the allowance of 100 which leads to the total of -400. 

i think a typical usage of ePiggy should be as follows:
1. user currently has $10 in his wallet. user does an add allowance command of $10.
2. User aims to spend $8 for the whole week, and does a set budget command of $8.
3. throughout the week, when the user does a add expense command, the amount will deducted from the budget, as well as adding it to the list of expenses. 

adding expenses that is over $10 should not be allowed because it is not possible since the user only has $10. If the amount goes to a negative, the user probably did not update ePiggy with a new allowance.

**Comment by kev-inc** [comment]
I will add the relevant checks to add expense to ensure that there is sufficient savings in ePiggy to deduct, if not, it will not allow the command.

**Comment by yunjun199321** [comment]
Wait. I think we mess up the idea of budget, expense and allowance. we have to make it clear during later meeting.
